### ISSUE TITLE
Utility functions appropriate?

### ISSUE THREAD

**Issue by jstaffans** [uswitch/lambada#3]
Thanks for taking a lot of the pain out of writing Lambda functions with Clojure! I have been using lambada to write a few Lambda functions and have produced some fairly re-usable utility functions for e.g. configuration management and reading input from SNS.

I was considering releasing some kind of "Lambda utils" library, but I could also just open a PR here. What do you think - do you want to keep this project very minimal or do you think it'd be appropriate to add what I have?

**Comment by ragnard** [comment]
Hi @jstaffans!

Great to hear you've found Lambada useful. In general, I think I'd like to keep lambada as minimal as possible. For example, I considered adding a simpler way to write lambda functions that receive/return JSON because that's such a common use-case. But then I'd have to either choose a JSON library for all users, a decisions a I don't think a library like this should make,  or create some kind of marshalling abstraction you could implement for any library, but that would have very little benefit over the 3 lines of code required by a user to do the JSON parsing. That said, if you have more details on the utility functions you have in mind I'd be happy to hear them.

**Comment by jstaffans** [comment]
After some more thought I think you're right, it's better to leave this library as it is - the utility functions I had in mind would introduce some library coupling. Thanks for the insight!
